apiVersion: aws.platform.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: cp1
  namespace: default
spec:
  crossplane:
    compositionRef:
      name: controlplane-adopt.aws.platform.upbound.io
  parameters:
    id: awsctpcp1
    managementMode: Provision
    region: eu-central-1
    naming: Deterministic
    version: "1.34"
    nodes:
      count: 2
      instanceType: t3.medium
